### ISSUE TITLE
You should use abstractions provided by Spring JPA Repository

### ISSUE THREAD

**Issue by ondrej-smola** [RonikCZ/ppj-projekt#1]
@Query("select i from Image as i where i.url=:url")
    public List<Image> findByUrl(@Param("url") String url);

Should be written without custom query

**Comment by RonikCZ** [comment]
Fixed in the last [commit](https://github.com/RonikCZ/ppj-projekt/commit/b7167c2046eb012117b001fd05ef8bc4050f3909)
